/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, ContractRunner } from "ethers";
import type {
  IUnicrowClaimRewards,
  IUnicrowClaimRewardsInterface,
} from "../../../contracts/interfaces/IUnicrowClaimRewards";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "distribute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUnicrowClaimRewards__factory {
  static readonly abi = _abi;
  static createInterface(): IUnicrowClaimRewardsInterface {
    return new Interface(_abi) as IUnicrowClaimRewardsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUnicrowClaimRewards {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUnicrowClaimRewards;
  }
}
