"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUnicrowStakingRewards__factory = exports.IUnicrowDispute__factory = exports.IUnicrowClaimRewards__factory = exports.IUnicrowClaim__factory = exports.IUnicrowArbitrator__factory = exports.IUnicrow__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IUnicrow__factory_1 = require("./IUnicrow__factory");
Object.defineProperty(exports, "IUnicrow__factory", { enumerable: true, get: function () { return IUnicrow__factory_1.IUnicrow__factory; } });
var IUnicrowArbitrator__factory_1 = require("./IUnicrowArbitrator__factory");
Object.defineProperty(exports, "IUnicrowArbitrator__factory", { enumerable: true, get: function () { return IUnicrowArbitrator__factory_1.IUnicrowArbitrator__factory; } });
var IUnicrowClaim__factory_1 = require("./IUnicrowClaim__factory");
Object.defineProperty(exports, "IUnicrowClaim__factory", { enumerable: true, get: function () { return IUnicrowClaim__factory_1.IUnicrowClaim__factory; } });
var IUnicrowClaimRewards__factory_1 = require("./IUnicrowClaimRewards__factory");
Object.defineProperty(exports, "IUnicrowClaimRewards__factory", { enumerable: true, get: function () { return IUnicrowClaimRewards__factory_1.IUnicrowClaimRewards__factory; } });
var IUnicrowDispute__factory_1 = require("./IUnicrowDispute__factory");
Object.defineProperty(exports, "IUnicrowDispute__factory", { enumerable: true, get: function () { return IUnicrowDispute__factory_1.IUnicrowDispute__factory; } });
var IUnicrowStakingRewards__factory_1 = require("./IUnicrowStakingRewards__factory");
Object.defineProperty(exports, "IUnicrowStakingRewards__factory", { enumerable: true, get: function () { return IUnicrowStakingRewards__factory_1.IUnicrowStakingRewards__factory; } });
