"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUnicrowClaim__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
        ],
        name: "claim",
        outputs: [
            {
                internalType: "uint256[5]",
                name: "",
                type: "uint256[5]",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256[]",
                name: "escrows",
                type: "uint256[]",
            },
        ],
        name: "claimMultiple",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "crowRewards_",
                type: "address",
            },
        ],
        name: "updateCrowRewards",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "protocolFeeAddress_",
                type: "address",
            },
        ],
        name: "updateProtocolFeeAddress",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "crowRewards_",
                type: "address",
            },
        ],
        name: "updateStakingRewards",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IUnicrowClaim__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IUnicrowClaim__factory = IUnicrowClaim__factory;
//# sourceMappingURL=IUnicrowClaim__factory.js.map