"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUnicrow__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
            {
                internalType: "uint16[4]",
                name: "split",
                type: "uint16[4]",
            },
            {
                internalType: "int16[2]",
                name: "consensus",
                type: "int16[2]",
            },
            {
                internalType: "uint64",
                name: "challengeStart",
                type: "uint64",
            },
            {
                internalType: "uint64",
                name: "challengeEnd",
                type: "uint64",
            },
        ],
        name: "challenge",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
        ],
        name: "getEscrow",
        outputs: [
            {
                components: [
                    {
                        internalType: "address",
                        name: "buyer",
                        type: "address",
                    },
                    {
                        internalType: "uint64",
                        name: "challengeExtension",
                        type: "uint64",
                    },
                    {
                        internalType: "address",
                        name: "seller",
                        type: "address",
                    },
                    {
                        internalType: "uint64",
                        name: "challengePeriodStart",
                        type: "uint64",
                    },
                    {
                        internalType: "address",
                        name: "marketplace",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "marketplaceFee",
                        type: "uint256",
                    },
                    {
                        internalType: "uint64",
                        name: "challengePeriodEnd",
                        type: "uint64",
                    },
                    {
                        internalType: "address",
                        name: "currency",
                        type: "address",
                    },
                    {
                        internalType: "uint16",
                        name: "claimed",
                        type: "uint16",
                    },
                    {
                        internalType: "int16[2]",
                        name: "consensus",
                        type: "int16[2]",
                    },
                    {
                        internalType: "uint16[4]",
                        name: "split",
                        type: "uint16[4]",
                    },
                    {
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256",
                    },
                    {
                        internalType: "string",
                        name: "paymentReference",
                        type: "string",
                    },
                ],
                internalType: "struct Escrow",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "sender",
                type: "address",
            },
            {
                components: [
                    {
                        internalType: "address",
                        name: "buyer",
                        type: "address",
                    },
                    {
                        internalType: "address",
                        name: "seller",
                        type: "address",
                    },
                    {
                        internalType: "address",
                        name: "marketplace",
                        type: "address",
                    },
                    {
                        internalType: "uint16",
                        name: "marketplaceFee",
                        type: "uint16",
                    },
                    {
                        internalType: "address",
                        name: "currency",
                        type: "address",
                    },
                    {
                        internalType: "uint32",
                        name: "challengePeriod",
                        type: "uint32",
                    },
                    {
                        internalType: "uint32",
                        name: "challengeExtension",
                        type: "uint32",
                    },
                    {
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256",
                    },
                    {
                        internalType: "string",
                        name: "paymentReference",
                        type: "string",
                    },
                ],
                internalType: "struct EscrowInput",
                name: "input",
                type: "tuple",
            },
            {
                internalType: "address",
                name: "arbitrator",
                type: "address",
            },
            {
                internalType: "uint16",
                name: "arbitratorFee",
                type: "uint16",
            },
        ],
        name: "pay",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
        ],
        name: "refund",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
        ],
        name: "release",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
        ],
        name: "setClaimed",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
            {
                internalType: "uint16[4]",
                name: "split",
                type: "uint16[4]",
            },
            {
                internalType: "int16[2]",
                name: "consensus",
                type: "int16[2]",
            },
        ],
        name: "settle",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint16[5]",
                name: "currentSplit",
                type: "uint16[5]",
            },
        ],
        name: "splitCalculation",
        outputs: [
            {
                internalType: "uint16[5]",
                name: "",
                type: "uint16[5]",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint16",
                name: "fee",
                type: "uint16",
            },
        ],
        name: "updateEscrowFee",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "governance",
                type: "address",
            },
        ],
        name: "updateGovernance",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IUnicrow__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IUnicrow__factory = IUnicrow__factory;
//# sourceMappingURL=IUnicrow__factory.js.map