/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, Interface } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
            {
                internalType: "uint16[2]",
                name: "validation",
                type: "uint16[2]",
            },
        ],
        name: "approveSettlement",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
        ],
        name: "challenge",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "escrowId",
                type: "uint256",
            },
            {
                internalType: "uint16[2]",
                name: "newSplit",
                type: "uint16[2]",
            },
        ],
        name: "offerSettlement",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IUnicrowDispute__factory {
    static abi = _abi;
    static createInterface() {
        return new Interface(_abi);
    }
    static connect(address, runner) {
        return new Contract(address, _abi, runner);
    }
}
export { IUnicrowDispute__factory };
//# sourceMappingURL=IUnicrowDispute__factory.js.map