"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnicrowDispute__factory = exports.UnicrowClaim__factory = exports.UnicrowArbitrator__factory = exports.Unicrow__factory = exports.FakeToken__factory = exports.interfaces = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.interfaces = __importStar(require("./interfaces"));
var FakeToken__factory_1 = require("./FakeToken__factory");
Object.defineProperty(exports, "FakeToken__factory", { enumerable: true, get: function () { return FakeToken__factory_1.FakeToken__factory; } });
var Unicrow__factory_1 = require("./Unicrow__factory");
Object.defineProperty(exports, "Unicrow__factory", { enumerable: true, get: function () { return Unicrow__factory_1.Unicrow__factory; } });
var UnicrowArbitrator__factory_1 = require("./UnicrowArbitrator__factory");
Object.defineProperty(exports, "UnicrowArbitrator__factory", { enumerable: true, get: function () { return UnicrowArbitrator__factory_1.UnicrowArbitrator__factory; } });
var UnicrowClaim__factory_1 = require("./UnicrowClaim__factory");
Object.defineProperty(exports, "UnicrowClaim__factory", { enumerable: true, get: function () { return UnicrowClaim__factory_1.UnicrowClaim__factory; } });
var UnicrowDispute__factory_1 = require("./UnicrowDispute__factory");
Object.defineProperty(exports, "UnicrowDispute__factory", { enumerable: true, get: function () { return UnicrowDispute__factory_1.UnicrowDispute__factory; } });
//# sourceMappingURL=index.js.map